# Generated by Django 2.0.2 on 2018-04-10 10:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('C', 'Confirmed'), ('S', 'Completed'), ('F', 'Failed')], default='Requested', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('appointment_time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('last_updated_on',),
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_updated_on',),
            },
        ),
        migrations.CreateModel(
            name='DirectCarePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('ALLERG', 'Allergist or Immunologist'), ('ANESTH', 'Anesthesiologist'), ('CARDIO', 'Cardiologist'), ('DERMAT', 'Dermatologist'), ('GASTRO', 'Gastroenterologist'), ('HEMATO', 'Hematologist/Oncologist'), ('IPHYSI', 'Internal Medicine Physician'), ('NEPHRO', 'Nephrologist'), ('NEUROL', 'Neurologist'), ('NEUROS', 'Neurosurgeon'), ('OBSTET', 'Obstetrician'), ('GYNECO', 'Gynecologist'), ('NUMIWF', 'Nurse Midwifery'), ('OPHYSI', 'Occupational Medicine Physician'), ('OPTHAL', 'Ophthalmologist'), ('ORMAXS', 'Oral and Maxillofacial Surgeon'), ('ORTHOS', 'Orthopaedic Surgeon'), ('OTOLAS', 'Otolaryngologist (Head and Neck Surgeon)'), ('PATHOL', 'Pathologist'), ('PEDIAT', 'Pediatrician'), ('PLASTS', 'Plastic Surgeon'), ('PODIAT', 'Podiatrist'), ('PSYCHI', 'Psychiatrist'), ('PUPHYS', 'Pulmonary Medicine Physician'), ('RADONC', 'Radiation Onconlogist'), ('DIARAD', 'Diagnostic Radiologist'), ('RHEUMA', 'Rheumatologist'), ('UROLOG', 'Urologist')], default=None, max_length=255, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('all_clinics', models.ManyToManyField(to='v1.Clinic')),
                ('available_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_doctors', to='v1.Clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_updated_on',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Third Gender')], default='M', max_length=100)),
                ('has_subscription', models.BooleanField(default=False)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_updated_on',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.DirectCarePlan')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Patient')),
            ],
            options={
                'ordering': ('last_updated_on',),
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='book_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Clinic'),
        ),
    ]
