# Generated by Django 2.0.2 on 2018-04-01 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('C', 'Confirmed'), ('S', 'Confirmed'), ('F', 'Failed')], default='Requested', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectCarePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('ALLERG', 'Allergist or Immunologist'), ('ANESTH', 'Anesthesiologist'), ('CARDIO', 'Cardiologist'), ('DERMAT', 'Dermatologist'), ('GASTRO', 'Gastroenterologist'), ('HEMATO', 'Hematologist/Oncologist'), ('IPHYSI', 'Internal Medicine Physician'), ('NEPHRO', 'Nephrologist'), ('NEUROL', 'Neurologist'), ('NEUROS', 'Neurosurgeon'), ('OBSTET', 'Obstetrician'), ('GYNECO', 'Gynecologist'), ('NUMIWF', 'Nurse Midwifery'), ('OPHYSI', 'Occupational Medicine Physician'), ('OPTHAL', 'Ophthalmologist'), ('ORMAXS', 'Oral and Maxillofacial Surgeon'), ('ORTHOS', 'Orthopaedic Surgeon'), ('OTOLAS', 'Otolaryngologist (Head and Neck Surgeon)'), ('PATHOL', 'Pathologist'), ('PEDIAT', 'Pediatrician'), ('PLASTS', 'Plastic Surgeon'), ('PODIAT', 'Podiatrist'), ('PSYCHI', 'Psychiatrist'), ('PUPHYS', 'Pulmonary Medicine Physician'), ('RADONC', 'Radiation Onconlogist'), ('DIARAD', 'Diagnostic Radiologist'), ('RHEUMA', 'Rheumatologist'), ('UROLOG', 'Urologist')], default=None, max_length=255, null=True)),
                ('description', models.CharField(choices=[('ALLERG', 'conducts the diagnosis and treatment of allergic conditions'), ('ANESTH', 'treats chronic pain syndromes; administers anesthesia and monitors the patient during surgery'), ('CARDIO', 'treats heart disease'), ('DERMAT', 'treats skin diseases, including some skin cancers'), ('GASTRO', 'treats stomach disorders'), ('HEMATO', 'treats diseases of the blood and blood forming tissues (oncology including cancer and other tumors)'), ('IPHYSI', 'treats diseases and disorders of internal structures of the body'), ('NEPHRO', 'treats kidney diseases'), ('NEUROL', 'treats diseases and disorders of the nervous system.'), ('NEUROS', 'conducts surgery of the nervous system.'), ('OBSTET', 'treats women during pregnancy and childbirth'), ('GYNECO', 'treats diseases of the female reproductive system and genital tract.'), ('NUMIWF', "manages a woman's health care, especially during pregnancy, delivery, and the postpartum period"), ('OPHYSI', 'diagnoses and treats work related disease or injury.'), ('OPTHAL', 'treats eye defects, injuries, and diseases.'), ('ORMAXS', 'surgically treats diseases, injuries, and defects of the hard and soft tissues of the face, mouth, and jaws.'), ('ORTHOS', 'preserves and restores the function of the musculoskeletal system.'), ('OTOLAS', 'treats diseases of the ear, nose, and throat,and some diseases of the head and neck, including facial plastic surgery.'), ('PATHOL', 'diagnoses and treats the study of the changes in body tissues and organs which cause or are caused by disease'), ('PEDIAT', 'treats infants, toddlers, children and teenagers.'), ('PLASTS', 'restores, reconstructs, corrects or improves in the shape and appearance of damaged body structures, especially the face.'), ('PODIAT', 'provides medical and surgical treatment of the foot.'), ('PSYCHI', 'treats patients with mental and emotional disorders. '), ('PUPHYS', 'diagnoses and treats lung disorders.'), ('RADONC', 'diagnoses and treats disorders with the use of diagnostic imaging, including X rays, sound waves, radioactive substances, and magnetic fields. '), ('DIARAD', 'diagnoses and medically treats diseases and disorders of internal structures of the body.'), ('RHEUMA', 'treats rheumatic diseases, or conditions characterized by inflammation, soreness and stiffness of muscles, and pain in joints and associated structures'), ('UROLOG', 'diagnoses and treats the male and female urinary tract and the male reproductive system')], default=None, max_length=255, null=True)),
                ('all_clinics', models.ManyToManyField(to='v1.Clinic')),
                ('available_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_doctors', to='v1.Clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=200)),
                ('has_subscription', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.DirectCarePlan')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='book_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Clinic'),
        ),
    ]
