# Generated by Django 2.0.2 on 2018-03-27 14:28

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
