# Generated by Django 2.0.2 on 2018-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('C', 'Confirmed'), ('S', 'Completed'), ('F', 'Failed')], default='Requested', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
