# Generated by Django 2.0.2 on 2018-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20180410_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
