# Generated by Django 2.0.2 on 2018-04-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20180414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_at',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_doctors', to='v1.Clinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ALLERG', 'Allergist or Immunologist'), ('ANESTH', 'Anesthesiologist'), ('CARDIO', 'Cardiologist'), ('DERMAT', 'Dermatologist'), ('GASTRO', 'Gastroenterologist'), ('HEMATO', 'Hematologist/Oncologist'), ('IPHYSI', 'Internal Medicine Physician'), ('NEPHRO', 'Nephrologist'), ('NEUROL', 'Neurologist'), ('NEUROS', 'Neurosurgeon'), ('OBSTET', 'Obstetrician'), ('GYNECO', 'Gynecologist'), ('NUMIWF', 'Nurse Midwifery'), ('OPHYSI', 'Occupational Medicine Physician'), ('OPTHAL', 'Ophthalmologist'), ('ORMAXS', 'Oral and Maxillofacial Surgeon'), ('ORTHOS', 'Orthopaedic Surgeon'), ('OTOLAS', 'Otolaryngologist (Head and Neck Surgeon)'), ('PATHOL', 'Pathologist'), ('PEDIAT', 'Pediatrician'), ('PLASTS', 'Plastic Surgeon'), ('PODIAT', 'Podiatrist'), ('PSYCHI', 'Psychiatrist'), ('PUPHYS', 'Pulmonary Medicine Physician'), ('RADONC', 'Radiation Onconlogist'), ('DIARAD', 'Diagnostic Radiologist'), ('RHEUMA', 'Rheumatologist'), ('UROLOG', 'Urologist')], default=None, max_length=255, null=True),
        ),
    ]
