# Generated by Django 2.0.2 on 2018-04-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20180402_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
