# Generated by Django 2.0.2 on 2018-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_remove_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Third Gender')], default='M', max_length=100),
        ),
    ]
