# Generated by Django 2.0.2 on 2018-04-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180415_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('C', 'Confirmed'), ('S', 'Completed'), ('F', 'Failed')], default='R', max_length=100),
        ),
    ]
