# Generated by Django 2.0.2 on 2018-04-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
