# Generated by Django 2.0.2 on 2018-04-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20180402_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('last_updated_on',)},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ('last_updated_on',)},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('last_updated_on',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('last_updated_on',)},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('last_updated_on',)},
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
